schema_id: 877cd6d9-f569-4fb7-9680-616758d9bb1d
schema_version: 1.0

shopping_list:
  items:
    fields:
      - name: !!str
      - amount: number
    # "units" is an optional extra field
    extras:
      - type: !!str
      - max_length: 1

